apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proposal-checker.fullname" . }}
  labels:
    {{- include "proposal-checker.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
